# Machine learning model price prediction and pickle files
The aim of this project is to undertsand the process or act of saving machine learning models

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
# importing data to dataframe
dft=pd.read_csv('housing price data//test.csv')
dftr=pd.read_csv('housing price data//train.csv')

In [3]:
# Overview of dataset
dft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1459 non-null   int64  
 1   MSSubClass     1459 non-null   int64  
 2   MSZoning       1455 non-null   object 
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64  
 5   Street         1459 non-null   object 
 6   Alley          107 non-null    object 
 7   LotShape       1459 non-null   object 
 8   LandContour    1459 non-null   object 
 9   Utilities      1457 non-null   object 
 10  LotConfig      1459 non-null   object 
 11  LandSlope      1459 non-null   object 
 12  Neighborhood   1459 non-null   object 
 13  Condition1     1459 non-null   object 
 14  Condition2     1459 non-null   object 
 15  BldgType       1459 non-null   object 
 16  HouseStyle     1459 non-null   object 
 17  OverallQual    1459 non-null   int64  
 18  OverallC

In [4]:
# specific review of LotArea
dft[dft.LotArea<5000].head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
11  1472         160       RM         21.0     1680   Pave   NaN      Reg   
12  1473         160       RM         21.0     1680   Pave   NaN      Reg   
13  1474         160       RL         24.0     2280   Pave   NaN      Reg   
14  1475         120       RL         24.0     2280   Pave   NaN      Reg   
23  1484         120       RL         43.0     3203   Pave   NaN      Reg   

   LandContour Utilities  ... ScreenPorch PoolArea PoolQC Fence MiscFeature  \
11         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
12         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
13         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
14         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
23         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  
11       0      2    2010       COD         Normal  
12       0      3    2010        WD         Normal  
13       0      6    2010        WD         Normal  
14       0      6    2010        WD         Normal  
23       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [5]:
#Random overview of MiscVal
dft.MiscVal.sample(5)

652    0
42     0
732    0
676    0
647    0
Name: MiscVal, dtype: int64

In [6]:
# jumping into training data
dftr.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [7]:
#selecting training data of interest and renaming its columns
df=dftr[['LotArea','SalePrice']]
df.columns=['area','price']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    1460 non-null   int64
 1   price   1460 non-null   int64
dtypes: int64(2)
memory usage: 22.9 KB


In [8]:
# creating model object
model= linear_model.LinearRegression() # y=mx+c

In [9]:
# fitting model with Xdf_train-area any Ydf_train-price
model.fit(df[['area']],df.price)

LinearRegression()

In [10]:
# checking coeffiecent - m
model.coef_

array([2.09997195])

In [11]:
# checking intercept - b
model.intercept_

158836.1518968766

In [12]:
# predict model values - area = 5000
model.predict([[5000]])

/home/sirembang/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([169336.01165541])

In [ ]:
# sample test and prediction data

In [20]:
sample=df.head(100)
sample.to_csv('sample area and price data.csv')

In [14]:
# test data Predict entire
test_output=dftr['LotArea'].head()
print(test_output.head())
test_output.info()
model.predict([[8450]])

0     8450
1     9600
2    11250
3     9550
4    14260
Name: LotArea, dtype: int64
<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: LotArea
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 168.0 bytes


/home/sirembang/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([176580.91488881])

## Saving a pickle file

After successfully training our model, we can save it in a pickle file for further usage without a need to train.

In [15]:
#loading library
import pickle

# creating an iterator object with write permission - model.pkl
with open('price_prediction_model.pkl', 'wb') as files:
    pickle.dump(model, files)

## Loading a pickle file 

In [16]:
# load saved model
with open('price_prediction_model.pkl' , 'rb') as f:
    mdl = pickle.load(f)

In [18]:
mdl.predict([[10000]])

/home/sirembang/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([179835.87141395])